services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - $PWD/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
        volumes:
            - $PWD/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
