services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - $PWD/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
